/* Service worker for the garage gallery — generated by generate_gallery.py.
 * Do not edit here; edit SW_TEMPLATE in the generator. */
var SHELL_CACHE = 'shell-b99b54783930';
var THUMB_CACHE = 'thumbs-v2';          /* deliberately unversioned: thumb urls
                                           are content-hashed and immutable, so
                                           entries stay valid across builds */
var SHELL = ["./", "index.html", "header.png"];
var THUMB_MAX = 300;

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(SHELL_CACHE)
      .then(function (c) { return c.addAll(SHELL); })
      .then(function () { return self.skipWaiting(); })
      .catch(function () { /* a missing shell file must not block install */ })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.map(function (k) {
        /* Drop superseded shell caches; never touch the thumb cache. */
        if (k === SHELL_CACHE || k === THUMB_CACHE) return null;
        return caches.delete(k);
      }));
    }).then(function () { return self.clients.claim(); })
  );
});

/* Insertion-order eviction, not true LRU: the Cache API preserves the order
 * entries were added, and tracking real recency would cost a write on every
 * cache hit. Good enough for "keep what I've been browsing". */
function trimThumbs(cache) {
  return cache.keys().then(function (keys) {
    if (keys.length <= THUMB_MAX) return null;
    var over = keys.length - THUMB_MAX;
    return Promise.all(keys.slice(0, over).map(function (k) { return cache.delete(k); }));
  });
}

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;

  var url;
  try { url = new URL(req.url); } catch (err) { return; }
  if (url.origin !== self.location.origin) return;   /* leave cross-origin alone */

  /* Thumbnails: cache-first, immutable, capped. */
  if (url.pathname.indexOf('/thumbs/') !== -1) {
    e.respondWith(
      caches.open(THUMB_CACHE).then(function (cache) {
        return cache.match(req).then(function (hit) {
          if (hit) return hit;
          return fetch(req).then(function (res) {
            if (res && res.ok) {
              cache.put(req, res.clone()).then(function () { return trimThumbs(cache); });
            }
            return res;
          });
        });
      })
    );
    return;
  }

  /* Everything else (the shell): network-first so a fresh publish always wins,
     falling back to cache so the app still opens with no connection. */
  e.respondWith(
    fetch(req).then(function (res) {
      if (res && res.ok) {
        var copy = res.clone();
        caches.open(SHELL_CACHE).then(function (c) { c.put(req, copy); });
      }
      return res;
    }).catch(function () {
      return caches.match(req).then(function (hit) {
        return hit || caches.match('index.html');   /* navigations land on the shell */
      });
    })
  );
});
